version: '3'

services:
    mlsploit-ui-service:
        build: .
        ports:
            - 5000:5000
            - 35729:35729
        volumes:
            - .:/app
            - app_node_modules:/app/node_modules

volumes:
    app_node_modules:
